# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.ks_c_cdf_direct <- function(n, B_steps, A_steps) {
    .Call(`_KSgeneral_ks_c_cdf_direct`, n, B_steps, A_steps)
}

.ks_c_cdf_Rcpp_legacy <- function(n) {
    .Call(`_KSgeneral_ks_c_cdf_Rcpp`, n)
}

KS2sample_c_Rcpp <- function(m, n, kind, M, q, w_vec, tol) {
    .Call(`_KSgeneral_KS2sample_c_Rcpp`, m, n, kind, M, q, w_vec, tol)
}

Kuiper2sample_Rcpp <- function(m, n, M, q) {
    .Call(`_KSgeneral_Kuiper2sample_Rcpp`, m, n, M, q)
}

Kuiper2sample_c_Rcpp <- function(m, n, M, q) {
    .Call(`_KSgeneral_Kuiper2sample_c_Rcpp`, m, n, M, q)
}

KS2sample_Rcpp <- function(m, n, kind, M, q, w_vec, tol) {
    .Call(`_KSgeneral_KS2sample_Rcpp`, m, n, kind, M, q, w_vec, tol)
}

